### ISSUE TITLE
Error when using session.multi driver

### ISSUE THREAD

**Issue by reefki** [ollieread/multitenancy#1]
Hi,

First of all thanks for this awesome package! Love it, probably the best and easiest multitenant package so far.

Everything works perfectly except when using `session.multi` driver, after logged in I got following error.

```
FatalThrowableError in SessionGuard.php line 23:
Call to a member function getPrimaryIdentifier() on null
```

**Comment by ollieread** [comment]
@reefki This is actually an issue I encountered myself. The issue is that you have the `Multitenancy::routes()` call inside the group that has the `web` middleware. This means that the auth middleware is called before the middleware that loads the current tenant.

The solution to this is something like this:

    protected function mapWebRoutes()
    {
        Multitenancy::routes(function (Router $router) {
            Route::middleware('web')
                ->namespace($this->namespace)
                ->group(base_path('routes/web.php'));
        });
    }

**Comment by reefki** [comment]
Perfect!

**Comment by ollieread** [comment]
I'm going to add this to th documentation for future reference.
